# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile_c.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
# from PySide2.QtCore import *
# from PySide2.QtGui import *
# from PySide2.QtWidgets import *
# from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2.QtGui import QColor
from PySide2.QtSql import QSqlDatabase, QSqlQuery
import Images_rc

import sys

class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                if not MainWindow.objectName():
                        MainWindow.setObjectName(u"MainWindow")
                MainWindow.resize(880, 880)
                MainWindow.setMinimumSize(QtCore.QSize(880, 880))
                MainWindow.setStyleSheet("background:  #16213E")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setSpacing(20)
                self.verticalLayout.setObjectName("verticalLayout")
                self.header = QtWidgets.QFrame(self.centralwidget)
                self.header.setMinimumSize(QtCore.QSize(0, 50))
                self.header.setMaximumSize(QtCore.QSize(16777215, 50))
                self.header.setStyleSheet("background: #0F3460")
                self.header.setObjectName("header")
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header)
                self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_4.setSpacing(0)
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.ControlButtons_2 = QtWidgets.QFrame(self.header)
                self.ControlButtons_2.setObjectName("ControlButtons_2")
                self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.ControlButtons_2)
                self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_6.setSpacing(15)
                self.horizontalLayout_6.setObjectName("horizontalLayout_6")
                self.close = QtWidgets.QPushButton(self.ControlButtons_2)
                self.close.setMinimumSize(QtCore.QSize(20, 0))
                self.close.setMaximumSize(QtCore.QSize(20, 16777215))
                self.close.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("Images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.close.setIcon(icon)
                self.close.setIconSize(QtCore.QSize(13, 16))
                self.close.setFlat(True)
                self.close.setObjectName("close")
                self.horizontalLayout_6.addWidget(self.close)
                self.expand = QtWidgets.QPushButton(self.ControlButtons_2)
                self.expand.setMinimumSize(QtCore.QSize(20, 25))
                self.expand.setMaximumSize(QtCore.QSize(20, 25))
                self.expand.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("Images/expand-arrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.expand.setIcon(icon1)
                self.expand.setIconSize(QtCore.QSize(20, 25))
                self.expand.setFlat(True)
                self.expand.setObjectName("expand")
                self.horizontalLayout_6.addWidget(self.expand)
                self.minimize = QtWidgets.QPushButton(self.ControlButtons_2)
                self.minimize.setMinimumSize(QtCore.QSize(20, 20))
                self.minimize.setMaximumSize(QtCore.QSize(20, 20))
                self.minimize.setText("")
                icon2 = QtGui.QIcon()
                icon2.addPixmap(QtGui.QPixmap("Images/minimize-sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.minimize.setIcon(icon2)
                self.minimize.setIconSize(QtCore.QSize(13, 16))
                self.minimize.setFlat(True)
                self.minimize.setObjectName("minimize")
                self.horizontalLayout_6.addWidget(self.minimize)
                self.horizontalLayout_4.addWidget(self.ControlButtons_2, 0, QtCore.Qt.AlignLeft)
                self.Logo_2 = QtWidgets.QFrame(self.header)
                self.Logo_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.Logo_2.setObjectName("Logo_2")
                self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Logo_2)
                self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_7.setSpacing(9)
                self.horizontalLayout_7.setObjectName("horizontalLayout_7")
                self.Learn_2 = QtWidgets.QLabel(self.Logo_2)
                font = QtGui.QFont()
                font.setFamily("Ubuntu Condensed")
                font.setPointSize(24)
                font.setBold(True)
                font.setItalic(True)
                font.setWeight(75)
                self.Learn_2.setFont(font)
                self.Learn_2.setStyleSheet("color: white")
                self.Learn_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
                self.Learn_2.setWordWrap(False)
                self.Learn_2.setObjectName("Learn_2")
                self.horizontalLayout_7.addWidget(self.Learn_2)
                self.Loop_2 = QtWidgets.QLabel(self.Logo_2)
                font = QtGui.QFont()
                font.setFamily("Ubuntu Condensed")
                font.setPointSize(24)
                font.setBold(True)
                font.setItalic(True)
                font.setWeight(75)
                self.Loop_2.setFont(font)
                self.Loop_2.setStyleSheet("color: #E94560")
                self.Loop_2.setObjectName("Loop_2")
                self.horizontalLayout_7.addWidget(self.Loop_2)
                self.horizontalLayout_4.addWidget(self.Logo_2)
                self.ProfilePhotoAndSettings_2 = QtWidgets.QFrame(self.header)
                self.ProfilePhotoAndSettings_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.ProfilePhotoAndSettings_2.setObjectName("ProfilePhotoAndSettings_2")
                self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ProfilePhotoAndSettings_2)
                self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_8.setSpacing(20)
                self.horizontalLayout_8.setObjectName("horizontalLayout_8")
                self.settings_2 = QtWidgets.QPushButton(self.ProfilePhotoAndSettings_2)
                self.settings_2.setMinimumSize(QtCore.QSize(45, 50))
                self.settings_2.setMaximumSize(QtCore.QSize(45, 50))
                self.settings_2.setStatusTip("")
                self.settings_2.setStyleSheet("background-color: #E94560;\n"
        "border-style: outset")
                self.settings_2.setText("")
                icon3 = QtGui.QIcon()
                icon3.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.settings_2.setIcon(icon3)
                self.settings_2.setIconSize(QtCore.QSize(30, 30))
                self.settings_2.setCheckable(False)
                self.settings_2.setAutoRepeat(False)
                self.settings_2.setAutoExclusive(False)
                self.settings_2.setAutoDefault(False)
                self.settings_2.setDefault(False)
                self.settings_2.setFlat(True)
                self.settings_2.setObjectName("settings_2")
                self.horizontalLayout_8.addWidget(self.settings_2)
                self.profilePhoto_2 = QtWidgets.QPushButton(self.ProfilePhotoAndSettings_2)
                self.profilePhoto_2.setMinimumSize(QtCore.QSize(50, 50))
                self.profilePhoto_2.setMaximumSize(QtCore.QSize(50, 50))
                self.profilePhoto_2.setAutoFillBackground(False)
                self.profilePhoto_2.setStyleSheet("")
                self.profilePhoto_2.setText("")
                icon4 = QtGui.QIcon()
                icon4.addPixmap(QtGui.QPixmap("C:/Desktop/59022631_810914472627047_3797622654492475392_n.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.profilePhoto_2.setIcon(icon4)
                self.profilePhoto_2.setIconSize(QtCore.QSize(50, 45))
                self.profilePhoto_2.setAutoDefault(False)
                self.profilePhoto_2.setDefault(False)
                self.profilePhoto_2.setFlat(True)
                self.profilePhoto_2.setObjectName("profilePhoto_2")
                self.horizontalLayout_8.addWidget(self.profilePhoto_2)
                self.horizontalLayout_4.addWidget(self.ProfilePhotoAndSettings_2, 0, QtCore.Qt.AlignRight)
                self.verticalLayout.addWidget(self.header)
                self.mainPage = QtWidgets.QFrame(self.centralwidget)
                self.mainPage.setMinimumSize(QtCore.QSize(0, 79))
                self.mainPage.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.mainPage.setStyleSheet("background-color: #16213E;")
                self.mainPage.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.mainPage.setFrameShadow(QtWidgets.QFrame.Raised)
                self.mainPage.setObjectName("mainPage")
                self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.mainPage)
                self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_6.setObjectName("verticalLayout_6")
                self.logo = QtWidgets.QFrame(self.mainPage)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
                self.logo.setSizePolicy(sizePolicy)
                self.logo.setMinimumSize(QtCore.QSize(0, 0))
                self.logo.setMaximumSize(QtCore.QSize(16777215, 300))
                self.logo.setStyleSheet("background-color: 16213e\n"
        "")
                self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
                self.logo.setObjectName("logo")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.logo)
                self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_2.setSpacing(0)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.frame_5 = QtWidgets.QFrame(self.logo)
                self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_5.setObjectName("frame_5")
                self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
                self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_7.setObjectName("verticalLayout_7")
                self.label_2 = QtWidgets.QLabel(self.frame_5)
                self.label_2.setMinimumSize(QtCore.QSize(309, 0))
                self.label_2.setMaximumSize(QtCore.QSize(309, 16777215))
                self.label_2.setStyleSheet("position: absolute;\n"
        "width: 232px;\n"
        "height: 36px;\n"
        "\n"
        "font-family: \'Righteous\';\n"
        "font-style: normal;\n"
        "font-weight: 400;\n"
        "font-size: 22px;\n"
        "line-height: 27px;\n"
        "display: flex;\n"
        "align-items: center;\n"
        "text-align: center;\n"
        "letter-spacing: 0.05em;\n"
        "\n"
        "color: #FFFFFF")
                self.label_2.setAlignment(QtCore.Qt.AlignCenter)
                self.label_2.setObjectName("label_2")
                self.verticalLayout_7.addWidget(self.label_2)
                spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout_7.addItem(spacerItem)
                self.verticalLayout_2.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter)
                self.frame = QtWidgets.QFrame(self.logo)
                self.frame.setEnabled(True)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
                self.frame.setSizePolicy(sizePolicy)
                self.frame.setMinimumSize(QtCore.QSize(50, 0))
                self.frame.setMaximumSize(QtCore.QSize(16777215, 79))
                self.frame.setStyleSheet("background-color: 16213e")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
                self.verticalLayout_4.setContentsMargins(30, 0, 15, 0)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.frame_4 = QtWidgets.QFrame(self.frame)
                self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_4.setObjectName("frame_4")
                self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
                self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.f2 = QtWidgets.QFrame(self.frame_4)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.f2.sizePolicy().hasHeightForWidth())
                self.f2.setSizePolicy(sizePolicy)
                self.f2.setObjectName("f2")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.f2)
                self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.label = QtWidgets.QLabel(self.f2)
                self.label.setMinimumSize(QtCore.QSize(140, 0))
                self.label.setMaximumSize(QtCore.QSize(130, 16777215))
                self.label.setStyleSheet("position: absolute;\n"
        "width: 194px;\n"
        "height: 29px;\n"
        "\n"
        "font-family: \'Righteous\';\n"
        "font-style: normal;\n"
        "font-weight: 400;\n"
        "font-size: 20px;\n"
        "line-height: 25px;\n"
        "display: flex;\n"
        "align-items: center;\n"
        "\n"
        "color: #FFFFFF;")
                self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
                self.label.setObjectName("label")
                self.horizontalLayout_2.addWidget(self.label)
                spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_2.addItem(spacerItem1)
                self.verticalLayout_5.addWidget(self.f2)
                self.verticalLayout_4.addWidget(self.frame_4)
                self.frame_2 = QtWidgets.QFrame(self.frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
                self.frame_2.setSizePolicy(sizePolicy)
                self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
                self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_2.setLineWidth(0)
                self.frame_2.setObjectName("frame_2")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
                self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_3.setSpacing(7)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.textEdit_3 = QtWidgets.QTextEdit(self.frame_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.textEdit_3.sizePolicy().hasHeightForWidth())
                self.textEdit_3.setSizePolicy(sizePolicy)
                self.textEdit_3.setMinimumSize(QtCore.QSize(0, 0))
                self.textEdit_3.setMaximumSize(QtCore.QSize(16777215, 30))
                self.textEdit_3.setStyleSheet("QTextEdit {\n"
        "    border-style: solid;\n"
        "    border-right-width: 0px;\n"
        "    border-bottom-width:2px;\n"
        "   border-top-width:0px;\n"
        "   border-left-width:0px;\n"
        "    background-color: rgb(22, 33, 62);\n"
        "    \n"
        "  \n"
        "    border-bottom-color: rgba(255, 255, 255, 0.5);\n"
        "   \n"
        "\n"
        "}\n"
        "QTextEdit[placeholderText=\"Search....\"] {\n"
        "    color:rgba(255, 255, 255, 0.5);  /* Set the color of the placeholder text */\n"
        "     /* Set the font style of the placeholder text */\n"
        "    font-size: 17px;\n"
        "}")
                self.textEdit_3.setMidLineWidth(0)
                self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.textEdit_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.textEdit_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
                self.textEdit_3.setPlaceholderText("Search....")
                self.textEdit_3.setObjectName("textEdit_3")
                self.verticalLayout_3.addWidget(self.textEdit_3, 0, QtCore.Qt.AlignVCenter)
                spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout_3.addItem(spacerItem2)
                self.verticalLayout_4.addWidget(self.frame_2)
                self.verticalLayout_2.addWidget(self.frame)
                self.verticalLayout_6.addWidget(self.logo)
                # self.frame_6 = QtWidgets.QFrame(self.mainPage)
                # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                # sizePolicy.setHorizontalStretch(0)
                # sizePolicy.setVerticalStretch(0)
                # sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
                # self.frame_6.setSizePolicy(sizePolicy)
                # self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
                # self.frame_6.setStyleSheet("background-color: #0f3460")
                # self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
                # self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
                # self.frame_6.setObjectName("frame_6")
                # self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_6)
                # self.verticalLayout_8.setObjectName("verticalLayout_8")
                # self.verticalLayout_6.addWidget(self.frame_6)
                self.frame_3 = QtWidgets.QFrame(self.mainPage)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
                self.frame_3.setSizePolicy(sizePolicy)
                self.frame_3.setMinimumSize(self.mainPage.frameWidth(),self.mainPage.height())
                self.frame_3.setStyleSheet("background-color: #16213e")
                self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_3.setObjectName("frame_3")
                
                # self.table.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
                self.verticalLayout_9.setObjectName("verticalLayout_9")
                self.table = QtWidgets.QTableWidget()
                self.verticalLayout_9.addWidget(self.table);
                self.verticalLayout_9.setAlignment(QtCore.Qt.AlignCenter);
                
                db = QSqlDatabase.addDatabase("QSQLITE")
                db.setHostName("localhost")
                db.setDatabaseName("mydatabase.db")
                if not db.open():
                        print("Cannot open database")
                        sys.exit(1)
                self.table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
                self.table.autoFillBackground();
                # self.table.;
                # self.table.setMinimumWidth(self.table.width())
                # self.table.setMinimumHeight(self.table.height())
                print(self.frame_3.width());
                print(self.frame_3.height());
                self.table.setMaximumWidth(1200)
                self.table.setMaximumHeight(500)
                self.on_table_changed(tablename=self.table);
                self.verticalLayout_6.addWidget(self.frame_3)
                self.verticalLayout.addWidget(self.mainPage)
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # def resizeEvent(self, event):
        #         print(self.frame_3.width())
        #         self.table.setMinimumWidth(self.frame_3.width()*0.5)
        #         self.table.setMinimumHeight(self.frame_3.height()*0.5)
        #         self.table.setMaximumWidth(self.frame_3.width()*0.7)
        #         self.table.setMaximumHeight(self.frame_3.height()*0.7)
        #         super().resizeEvent(event)
        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.Learn_2.setText(_translate("MainWindow", "Learn"))
                self.Loop_2.setText(_translate("MainWindow", "Loop"))
                self.label_2.setText(_translate("MainWindow", "Aya\n"
        " Abd El-Monem\n"
        " Gaber"))
                self.label.setText(_translate("MainWindow", "Courses"))
                self.textEdit_3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>hfgfg</p></body></html>"))
        def on_table_changed(self, tablename):
                print(f"Table changed: {tablename}")
                # Clear the table
                self.table.clearContents()
                self.table.setRowCount(0)
                # Refetch data from the database
                query = QSqlQuery()
                query.prepare("SELECT * from Persons3;")
                if not query.exec_():
                        print("Cannot execute query")
                        sys.exit(1)
                
                # Repopulate the table with data from the database
                self.table.setColumnCount(query.record().count())
                # self.table.setRowCount(query.size())
                
                self.table.setHorizontalHeaderLabels([query.record().fieldName(i) for i in range(query.record().count())])
                
                while query.next():
                        row = self.table.rowCount()
                        self.table.insertRow(row)
                        for column in range(query.record().count()):
                                item = QtWidgets.QTableWidgetItem(str(query.value(column)))
                                item.setTextAlignment(QtCore.Qt.AlignCenter);
                                # item(QColor(255, 255, 255))  # Set text color to blue
                                self.table.setItem(row, column, item)
                odd_color = QColor(22,33,62) # light gray
                even_color = QColor(15, 52, 96)  # darker gray
                print(self.table.rowCount())
                # Use a stylesheet to set background colors for odd and even rows
                self.table.setStyleSheet(f"QTableView {{ alternate-background-color: {odd_color.name()};background-color: {even_color.name()};border:none;padding:0;}} "
                                        f"QTableWidget::item {{color: white;border:none;}}"
                                        "QTableWidget::section {{ border: none;padding:none; }}"
                                        # f"QHeaderView  {{ background-color: {even_color.name()}; }} "
                                        # f"QHeaderView::item {{color: white;}}"
                                        )
                self.table.horizontalHeader().setStyleSheet(f"QHeaderView::section {{color: white; background-color:{odd_color.name()}; border: none; }}"
                                                            "QHeaderView::section:hover { background-color: odd_color.name(); border: none;padding:none; }")
                self.table.verticalHeader().setVisible(False);
                # self.table.verticalScrollBar().setStyleSheet("QScrollBar:vertical { width: 10px; }")
                # self.table.verticalScrollBar().setStyleSheet("QScrollBar:vertical { width: 10px; } QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical { height: 0px; }")
                # self.table.verticalScrollBar().
                self.table.verticalScrollBar().setStyleSheet("""QScrollBar:vertical {
                width: 2px;
                background: #f1f1f1;
                }

                QScrollBar::handle:vertical {
                background: #888;
                }

                QScrollBar::add-line:vertical {
                border: 2px solid gray;
                background: #f1f1f1;
                }

                QScrollBar::sub-line:horizontal {
                border: 2px solid gray;
                background: #f1f1f1;
                }

                QScrollBar::handle:hover:vertical {
                background: #555;
                }"""
                )
                # self.table.horizontalHeader().setStyleSheet(
                #                         )
                self.table.setAlternatingRowColors(True)
# 0f3460
# 16213e
if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
